### ISSUE TITLE
Provided example causes template compile error over users

### ISSUE THREAD

**Issue by darkpixel** [salt-formulas/salt-formula-postgresql#10]
Pillar data:
```
[root@salt /srv/salt/base]# salt 'ripley' pillar.items

ripley:
    ----------
    postgresql:
        ----------
        server:
            ----------
            bind:
                ----------
                address:
                    127.0.0.1
                port:
                    5432
                protocol:
                    tcp
            clients:
                - 127.0.0.1
            database:
                ----------
                encoding:
                    UTF8
                name:
                    mytestdb
                users:
                    |_
                      ----------
                      host:
                          localhost
                      name:
                          mytestdb
                      password:
                          ahxaGhiel7fe
                      rights:
                          all privileges
            enabled:
                True
            version:
                9.5
```
Produces:
```
[root@salt /srv/salt/base]# salt 'ripley' state.highstate
ripley:
    Data failed to compile:
----------
    Rendering SLS 'base:postgresql.server' failed: Jinja variable 'str object' has no attribute 'users'
/var/cache/salt/minion/files/base/postgresql/_database.sls(1):
---
{%- for user in database.users %}    <======================
{% if not grains.get('noservices', False) %}
postgresql_user_{{ svr_name|default('localhost') }}_{{ database_name }}_{{ user.name }}:
  postgres_user.present:
    - name: {{ user.name }}
    - user: postgres
[...]
---


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 1
-------------------------------------------
ERROR: Minions returned with non-zero exit code
[root@salt /srv/salt/base]# 
```

Actual pillar file:
```
postgresql:
  server:
    enabled: true
    version: 9.5
    bind:
      address: 127.0.0.1
      port: 5432
      protocol: tcp
    clients:
    - 127.0.0.1
    database:
      name: 'mytestdb'
      encoding: 'UTF8'
      users:
      - name: 'mytestdb'
        password: ahxaGhiel7fe
        host: 'localhost'
        rights: 'all privileges'
```

Cloned from master a few minutes ago.  Commit a7ceccb3158

**Comment by fpytloun** [comment]
Hello,

I think your pillar is not correct, database is supposed to be dict like this:
```
    database:
      mytestdb:
        encoding: 'UTF8'
        users:
        - name: 'mytestdb'
          password: ahxaGhiel7fe
          host: 'localhost'
          rights: 'all privileges'
```
https://github.com/salt-formulas/salt-formula-postgresql/blob/master/postgresql/server.sls#L70

Documentation is not correct, I will fix it.
