### ISSUE TITLE
why slave have postgresql.conf in data dir?

### ISSUE THREAD

**Issue by yongzhang** [salt-formulas/salt-formula-postgresql#13]
Hi, 

Here's the part of slave.sls code regarding postgresql.conf, I'm wondering why {{ cluster.dir.data }}/postgresql.conf is there? Is this should be {{ cluster.dir.config }}/postgresql.conf?

```
{{ cluster.dir.data }}/postgresql.conf:
  file.managed:
  - source: salt://postgresql/files/{{ cluster.version }}/postgresql.conf.{{ grains.os_family }}
  - template: jinja
  - user: postgres
  - group: postgres
  - defaults:
      postgresql_version: {{ cluster.version }}
  - mode: 600
  - require:
    - cmd: restore_postgresql_cluster

postgresql_slave_service:
  service.running:
  - name: {{ cluster.service }}
  - enable: true
  - watch:
    - file: {{ cluster.dir.data }}/postgresql.conf
    - file: {{ cluster.dir.data }}/recovery.conf
  - require:
    - cmd: restore_postgresql_cluster
    - file: {{ cluster.dir.data }}/recovery.conf
```
