### ISSUE TITLE
postgresql 9.5 can bind only on 127.0.0.1 (Ubuntu)

### ISSUE THREAD

**Issue by Morsicus** [salt-formulas/salt-formula-postgresql#18]
Hi, 

## Summary
When I specify a ip_address to bind, postgresql don't start.

## Node details
- Ubuntu 16.04
- Postgresql 9.5

## Examples
pillar example working:
```yaml
postgresql:
  server:
    clients:
      - 127.0.0.1
    bind:
      address: 127.0.0.1
      port: 5432
      protocol: tcp
    enabled: true
    database:
      testing:
        enabled: true
        encoding: 'UTF8'
        locale: 'en_US'
        users:
        - name: test
          password: test
          host: localhost
          createdb: true
          rights: all privileges
```

pillar example not working:
```yaml
postgresql:
  server:
    clients:
      -  192.168.50.20
    bind:
      address: 192.168.50.20
      port: 5432
      protocol: tcp
    enabled: true
    database:
      testing:
        enabled: true
        encoding: 'UTF8'
        locale: 'en_US'
        users:
        - name: test
          password: test
          host: localhost
          createdb: true
          rights: all privileges
```

## Expected behaviour

It should work.

## Possible fix
I think the issue is here,https://github.com/salt-formulas/salt-formula-postgresql/blob/master/postgresql/files/9.5/postgresql.conf.Debian#L62, listen_addresses should be a comma-separeted string (https://www.postgresql.org/docs/9.5/static/runtime-config-connection.html)

String configuration should be:
listen_addresses = 'localhost, 192.168.50.20' and not 
listen_addresses = 'localhost', '192.168.50.20'
