### ISSUE TITLE
No package postgresql93-contrib available

### ISSUE THREAD

**Issue by mturra-Pro** [salt-formulas/salt-formula-postgresql#26]
I'm trying the formula on CentOS 7 with this pillar

```yaml
postgresql:
  server:
    enabled: true
    version: 11
    bind:
      address: 127.0.0.1
      port: 5432
      protocol: tcp
    clients:
      - 127.0.0.1
    database:
      databasename:
        encoding: 'UTF8'
        locale: 'cs_CZ'
        users:
          - name: 'username'
            password: 'password'
            host: 'localhost'
            rights: 'all privileges'
  cluster:
    enabled: false
```

I get this error:
```
          ID: postgresql_packages
    Function: pkg.installed
        Name: postgresql93-server
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - Running scope as unit run-1365.scope.
                    Loaded plugins: fastestmirror
                    Loading mirror speeds from cached hostfile
                     * base: mirrors.prometeus.net
                     * epel: mirrors.n-ix.net
                     * extras: mirrors.prometeus.net
                     * updates: mirrors.prometeus.net
                    No package postgresql93-server available.
                    Error: Nothing to do
```

I think a repo like this https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm must be installed?
